# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core'

# [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'

pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText', 
  'RCTImage',
  'RCTNetwork'
  # Add any other subspecs you want to use in your project
]

target 'Starter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Starter

  target 'StarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end